//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tudonastorev2.mainVITLabService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientEntity", Namespace="http://schemas.datacontract.org/2004/07/TudoNaStoreEntity")]
    [System.SerializableAttribute()]
    public partial class ClientEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressComField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNghField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressStaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientRegionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientStatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeolocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashControlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstagramIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tudonastorev2.mainVITLabService.ClientType TypeCliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhatsAppField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCom {
            get {
                return this.AddressComField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressComField, value) != true)) {
                    this.AddressComField = value;
                    this.RaisePropertyChanged("AddressCom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressNgh {
            get {
                return this.AddressNghField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNghField, value) != true)) {
                    this.AddressNghField = value;
                    this.RaisePropertyChanged("AddressNgh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressNum {
            get {
                return this.AddressNumField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNumField, value) != true)) {
                    this.AddressNumField = value;
                    this.RaisePropertyChanged("AddressNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressSta {
            get {
                return this.AddressStaField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressStaField, value) != true)) {
                    this.AddressStaField = value;
                    this.RaisePropertyChanged("AddressSta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientContactName {
            get {
                return this.ClientContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientContactNameField, value) != true)) {
                    this.ClientContactNameField = value;
                    this.RaisePropertyChanged("ClientContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientContactNumber {
            get {
                return this.ClientContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientContactNumberField, value) != true)) {
                    this.ClientContactNumberField = value;
                    this.RaisePropertyChanged("ClientContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientHost {
            get {
                return this.ClientHostField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientHostField, value) != true)) {
                    this.ClientHostField = value;
                    this.RaisePropertyChanged("ClientHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientPhoneNumber {
            get {
                return this.ClientPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientPhoneNumberField, value) != true)) {
                    this.ClientPhoneNumberField = value;
                    this.RaisePropertyChanged("ClientPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientRegionID {
            get {
                return this.ClientRegionIDField;
            }
            set {
                if ((this.ClientRegionIDField.Equals(value) != true)) {
                    this.ClientRegionIDField = value;
                    this.RaisePropertyChanged("ClientRegionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientStatusID {
            get {
                return this.ClientStatusIDField;
            }
            set {
                if ((this.ClientStatusIDField.Equals(value) != true)) {
                    this.ClientStatusIDField = value;
                    this.RaisePropertyChanged("ClientStatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFullName {
            get {
                return this.CustomerFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerFullNameField, value) != true)) {
                    this.CustomerFullNameField = value;
                    this.RaisePropertyChanged("CustomerFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookID {
            get {
                return this.FacebookIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookIDField, value) != true)) {
                    this.FacebookIDField = value;
                    this.RaisePropertyChanged("FacebookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullAdress {
            get {
                return this.FullAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.FullAdressField, value) != true)) {
                    this.FullAdressField = value;
                    this.RaisePropertyChanged("FullAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Geolocation {
            get {
                return this.GeolocationField;
            }
            set {
                if ((object.ReferenceEquals(this.GeolocationField, value) != true)) {
                    this.GeolocationField = value;
                    this.RaisePropertyChanged("Geolocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashControl {
            get {
                return this.HashControlField;
            }
            set {
                if ((object.ReferenceEquals(this.HashControlField, value) != true)) {
                    this.HashControlField = value;
                    this.RaisePropertyChanged("HashControl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstagramID {
            get {
                return this.InstagramIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InstagramIDField, value) != true)) {
                    this.InstagramIDField = value;
                    this.RaisePropertyChanged("InstagramID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialNumber {
            get {
                return this.SocialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SocialNumberField, value) != true)) {
                    this.SocialNumberField = value;
                    this.RaisePropertyChanged("SocialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tudonastorev2.mainVITLabService.ClientType TypeCli {
            get {
                return this.TypeCliField;
            }
            set {
                if ((this.TypeCliField.Equals(value) != true)) {
                    this.TypeCliField = value;
                    this.RaisePropertyChanged("TypeCli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhatsApp {
            get {
                return this.WhatsAppField;
            }
            set {
                if ((object.ReferenceEquals(this.WhatsAppField, value) != true)) {
                    this.WhatsAppField = value;
                    this.RaisePropertyChanged("WhatsApp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zipcode {
            get {
                return this.ZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipcodeField, value) != true)) {
                    this.ZipcodeField = value;
                    this.RaisePropertyChanged("Zipcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientType", Namespace="http://schemas.datacontract.org/2004/07/TudoNaStoreEntity")]
    public enum ClientType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        J = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/mainVITLabService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mainVITLabService.ClientServiceInterface")]
    public interface ClientServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientServiceInterface/GetClient", ReplyAction="http://tempuri.org/ClientServiceInterface/GetClientResponse")]
        Tudonastorev2.mainVITLabService.ClientEntity GetClient(string hashClient, string host);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientServiceInterface/GetClient", ReplyAction="http://tempuri.org/ClientServiceInterface/GetClientResponse")]
        System.Threading.Tasks.Task<Tudonastorev2.mainVITLabService.ClientEntity> GetClientAsync(string hashClient, string host);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientServiceInterface/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ClientServiceInterface/GetDataUsingDataContractResponse")]
        Tudonastorev2.mainVITLabService.CompositeType GetDataUsingDataContract(Tudonastorev2.mainVITLabService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientServiceInterface/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ClientServiceInterface/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Tudonastorev2.mainVITLabService.CompositeType> GetDataUsingDataContractAsync(Tudonastorev2.mainVITLabService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientServiceInterfaceChannel : Tudonastorev2.mainVITLabService.ClientServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceInterfaceClient : System.ServiceModel.ClientBase<Tudonastorev2.mainVITLabService.ClientServiceInterface>, Tudonastorev2.mainVITLabService.ClientServiceInterface {
        
        public ClientServiceInterfaceClient() {
        }
        
        public ClientServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tudonastorev2.mainVITLabService.ClientEntity GetClient(string hashClient, string host) {
            return base.Channel.GetClient(hashClient, host);
        }
        
        public System.Threading.Tasks.Task<Tudonastorev2.mainVITLabService.ClientEntity> GetClientAsync(string hashClient, string host) {
            return base.Channel.GetClientAsync(hashClient, host);
        }
        
        public Tudonastorev2.mainVITLabService.CompositeType GetDataUsingDataContract(Tudonastorev2.mainVITLabService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Tudonastorev2.mainVITLabService.CompositeType> GetDataUsingDataContractAsync(Tudonastorev2.mainVITLabService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
